name: Sync To Gitee

on:
  push:
    branches-ignore: 
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: https://github.com/AvaotaSBC/Avaota-A1.git
          destination-repo: git@gitee.com:avaotasbc/avaota-a1.git
